-- 003_create_pim_material_table.sql
-- Create pim.material table for BeProduct material webhook ingestion

create table if not exists pim.material (
    id serial primary key,
    beproduct_material_id uuid unique not null,
    header_number text not null,
    header_name text not null,
    beproduct_folder_id uuid,
    folder_name text,
    brand text,
    material_type text,
    fabric_group text,
    fabric_name_cn text,
    status text,
    season_year text,
    composition jsonb,
    back_content jsonb,
    care_instructions jsonb,
    properties_fabric text,
    supplier text,
    supplier_code text,
    material_reference_code text,
    lead_time text,
    material_width numeric,
    material_full_width numeric,
    material_weight numeric,
    unit_of_measure_base text,
    material_purchase_price numeric,
    currency_lookup text,
    unit_of_measure_purchase_price text,
    costing_price_usd numeric,
    material_yield numeric,
    material_moq numeric,
    material_mcq numeric,
    surcharge_moq numeric,
    surcharge_mcq numeric,
    core_3d_material boolean,
    main_image_preview text,
    main_image_url text,
    detail_image_preview text,
    detail_image_url text,
    notes text,
    created_by text,
    beproduct_created_at timestamptz,
    modified_by text,
    beproduct_modified_at timestamptz,
    deleted boolean default false,
    raw_beproduct_data jsonb,
    created_at timestamptz default now(),
    updated_at timestamptz default now()
);

create index if not exists idx_material_header_number on pim.material(header_number);
create index if not exists idx_material_deleted on pim.material(deleted);